export const routes = {
  home: '/',
  products: '/productos',
  category: '/categoria/:slug',
  checkout: '/checkout',
  order: '/pedido/:orderNumber',
  recoverOrder: '/recuperar-pedido',
  consumerWithdrawal: '/arrepentimiento',
  consumerWithdrawalStatus: '/arrepentimiento/consulta',
  admin: '/admin',
  adminLogin: '/admin/login',
  adminProducts: '/admin/productos',
  adminCategories: '/admin/categorias',
  adminOrders: '/admin/pedidos',
  adminConsumerWithdrawals: '/admin/arrepentimientos',
  adminCustomers: '/admin/clientes',
  adminSettings: '/admin/configuracion',
  adminProfile: '/admin/perfil',
  adminCustomerDetail: (customerId: string) => `/admin/clientes/${encodeURIComponent(customerId)}`,
  adminOrderDetail: (orderId: string) => `/admin/pedidos/${encodeURIComponent(orderId)}`,
  adminConsumerWithdrawalDetail: (requestId: string) =>
    `/admin/arrepentimientos/${encodeURIComponent(requestId)}`,
  adminCategoryNew: '/admin/categorias/nueva',
  adminCategoryEdit: (categoryId: string) =>
    `/admin/categorias/${encodeURIComponent(categoryId)}/editar`,
  adminProductNew: '/admin/productos/nuevo',
  adminProductEdit: (productId: string) => `/admin/productos/${encodeURIComponent(productId)}/editar`,
  orderPath: (orderNumber: string) => `/pedido/${encodeURIComponent(orderNumber)}`,
} as const
